name: photos

on:
  workflow_run:
    workflows:
      - photo-testing
    types:
      - completed

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/master'

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
    steps:
      - uses: actions/checkout@v4
      # todo build steps
      # deploy
      - name: Pulumi dependencies
        working-directory: pulumi
        run: npm ci
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: lysz210/photos/dev
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
