name: Deploy photos

on:
  push:
    branches:
      - LYS-19-rilasciare-la-sottosezione-documentazione
#      - master

jobs:
#  test:
#    uses: ./.github/workflows/test.yaml
#  deploy:
#    needs:
#      - test
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ ubuntu-latest ]
#        node: [ 22 ]
#    steps:
#      - uses: actions/checkout@v4
#      # todo build steps
#      # deploy
#      - name: Pulumi dependencies
#        working-directory: pulumi
#        run: npm ci
#      - uses: pulumi/actions@v6
#        with:
#          command: up
#          stack-name: lysz210/photos/dev
#          work-dir: pulumi
#        env:
#          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  docs:
#    needs:
#      - test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 22 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Generate documentations
        run: npm run docs
      - name: Upload documentation to artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ${{ github.workspace }}/.reports/docs
          if-no-files-found: error
  pages:
    needs:
      - docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 22 ]
    steps:
      - name: Download docs
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs