name: photo-testing

on:
  workflow_call:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Unit tests
        run: npm run test:unit
      - name: Run Code Coverage
        run: npm run coverage
      - name: Run Bdd
        run: npm run test:bdd