name: photo-testing

on:
  workflow_call:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Unit tests with coverage
        run: npm run test:unit
      - name: Upload unit tests results to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit
          path: .reports/unit
          if-no-files-found: error
      - name: Upload code coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .reports/coverage
          if-no-files-found: error
      - name: Run Bdd
        run: npm run test:bdd
      - name: Upload Bdd test results to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bdd
          path: .reports/bdd
          if-no-files-found: error